apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: spacehub-frontend
  namespace: spacehub-frontend
spec:
  releaseName: spacehub-frontend
  chart:
    spec:
      chart: spacehub-frontend
      sourceRef:
        kind: HelmRepository
        name: spacehub-frontend
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    service:
      type: LoadBalancer
