apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: spacehub-frontend
  namespace: spacehub-frontend
spec:
  chart:
    spec:
      version: ">=1.0.1"
  test:
    enable: false
